apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
data:
  APP_VERSION: {{ .Values.app.version | quote }}
  FLASK_ENV: "production"
