apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
