apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: three-tier
type: Opaque
stringData:
  DB_HOST: "YOUR-RDS-ENDPOINT"
  DB_USER: "admin"
  DB_PASSWORD: "YOUR-PASSWORD"
  DB_NAME: "threetierdb"